baseurl = "/"
languageCode = "en-us"
author = 'Rafael Passos @Auyer'
theme = "hello-friend"
paginate = 5
publishDir = "publish"
googleAnalytics = "UA-122073247-1" 

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "news"
  # "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "MassMover Bot"
    subtitle = "A Discord multi-bot capable of moving users quickly"
    keywords = ""
    copyright = ""
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Mass Mover Multi-Bot"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "news"
        name = "News"
        url = "/news"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"